### ISSUE TITLE
Swagger definition

### ISSUE THREAD

**Issue by dguido** [macadmins/simpleMDMpy#30]
This really ought to be something that SimpleMDM makes for themselves, but it would open a lot of possibilities for library development, testing, and maintenance.

https://swagger.io/docs/swagger-inspector/how-to-create-an-openapi-definition-using-swagger/

**Comment by bryanheinz** [comment]
thanks for your feedback. however, this is out of scope for this project. there appears to already be a feature request for SimpleMDM to implement this **[here](https://suggestions.simplemdm.com/forums/204404-suggestions/suggestions/38483821-swagger-documentation-for-api)** that you can upvote.

-bryan
