### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by jcfrt** [macadmins/simpleMDMpy#57]
While testing the `dev` branch I noticed a problem with pagination: the `starting_after` parameter keeps increasing, but never resets back to 0 which leads to incomplete data being returned after subsequent calls to that same method. 

That is due to the fact that a python dictionary is defined as the default parameter in the _get_data method. 
This is not a good practice ([example reference](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/)) and should be set to None instead.

**Comment by MagerValp** [comment]
Fixedin #58 and #59
